Resources:
  CommentsTable:
    Type: 'AWS::DynamoDB::Table'    
    Properties:
      TableName: "${self:provider.environment.tablePrefix}-Comments"
      BillingMode: PAY_PER_REQUEST  
      AttributeDefinitions:
        - AttributeName: visible
          AttributeType: N
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: visible
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

Outputs:
  CommentsTable:
    Value:
      Ref: CommentsTable
